### ISSUE TITLE
Feature Suggestion: 아이디 중복을 확인할 수 있는 API가 필요합니다. 

### ISSUE THREAD

**Issue by devJang** [woowacourse/javascript-subway#1]
https://woowacourse.slack.com/archives/C01KX4WCV5X/p1616111219066100

**Comment by sunhpark42** [comment]
## 🤦🏻 이슈 내용
* 아이디 중복을 확인할 수 있는 API가 있으면 좋을 것 같습니다.
* 현재는 중복된 이메일을 입력후, 가입버튼을 눌러야만 이메일 중복을 확인할 수 있습니다.
* 사용자가 '가입버튼'을 누르는 것은 폼 작성 완료 및 제출, 즉 행위의 종료를 의미합니다. 종료 이후 상위에서 발생한 에러를 반환하고 재입력하는 것이 불편하다고 생각합니다. 또한 이메일 입력의 경우 상단에서 이루어지기 때문에, 불필요한 시선 이동이 발생합니다.
 * email input에서 focus out 되거나 ‘중복확인’ 버튼을 클릭해서 아이디만을 따로 확인하는 것이 시선의 이동이 적고, 에러를 확인하고 바로 수정하기에 더 편리하다고 생각합니다.

 * 현재 있는 API를 이용해서는 가입 버튼을 누르기 전에는 확인이 불가능 하고, 돌려서 사용하는 방법으로는 로그인 API를 이용해서 확인할 수 있는데(현재 아이디가 없을 시 500에러, 비밀번호가 틀렸을 시 401 에러를 반환합니다), 아이디가 없을 시 발생하는 에러는 서버에서 처리가 안된 에러로 발생하는 것이고 변경될 수 있으므로 적합하지 않다고 생각합니다.

## 📃 이슈 재현
* 회원가입시
* 이름입력 -> 중복된 이메일 입력 -> 비밀번호 입력 -> 비밀번호 확인 입력 -> 비밀번호 유효성 판단 -> 확인 버튼 -> 이메일 중복 에러 반환 -> 유효한 이메일 입력 -> 회원가입 성공
* 중복된 이메일을 계속해서 입력하는 경우, '회원가입 확인 버튼'을 누를 때 마다 이메일 중복 에러를 표시

## 🕵🏼 기대 결과
* 이름입력 -> 중복된 이메일 입력 -> 이메일 입력칸 벗어남/아이디 중복 확인 버튼 클릭 ->  이메일 중복 에러 반환 -> 유효한 이메일 입력 -> 비밀번호 입력 -> 비밀번호 확인 입력 -> 비밀번호 유효성 판단 -> 확인버튼 -> 회원가입성공
* 사용자가 중복된 이메일임을 입력 후 바로 확인 할 수 있음.

## 😢 실제 결과
* 이슈 재현과 동일

**Comment by gracefulBrown** [comment]
중복 이메일 체크 기능 배포되었습니다~ 확인해주세요 :)

중복 이메일 체크 - 성공
http://15.164.230.130:8080/docs/index.html#_%EC%A4%91%EB%B3%B5_%EC%95%84%EC%9D%B4%EB%94%94_%EC%B2%B4%ED%81%AC_%EC%84%B1%EA%B3%B5

중복 이메일 체크 - 실패
http://15.164.230.130:8080/docs/index.html#_%EC%A4%91%EB%B3%B5_%EC%95%84%EC%9D%B4%EB%94%94_%EC%B2%B4%ED%81%AC_%EC%8B%A4%ED%8C%A8
