### ISSUE TITLE
API에 HTTPS 적용이 필요합니다

### ISSUE THREAD

**Issue by Puterism** [woowacourse/javascript-subway#2]
## 🤦🏻 이슈 내용

안녕하세요! API에 **https 적용**이 필요해보여서 이슈 올립니다!
구현한 걸 배포할 때 보통 Github Pages를 사용하는데, https로 배포됩니다.
이 때문에, API 요청을 보내면 Mixed Content 문제로 응답을 받을 수 없는 상황이 생깁니다.
(http에서 https로 요청을 보내는 것은 가능하지만, https에서 http로 요청을 보낼 수 없는 상태입니다.)

## 📃 이슈 재현
- https로 배포된 페이지에서 통상적인 API 요청을 보낸다.

## 🕵🏼 기대 결과
- 정상적인 응답을 받고, 페이지가 의도대로 정상 동작한다.

## 😢 실제 결과 
![image](https://user-images.githubusercontent.com/2542730/111751760-3517d580-88d8-11eb-8bd7-64504b63d661.png)
- 위 에러 메시지와 함께 정상적인 응답을 받을 수 없다.

@jho2301

**Comment by gracefulBrown** [comment]
임시 도메인으로 https 적용을 했습니다.
월요일 이후 최종 결정된 도메인을 공지할께요 :)
그 전까지 이 도메인으로 연동 연습 하시면 될 것 같아요 :) 

https://www.boorownie.com/docs/index.html
