### ISSUE TITLE
DELETE method 오류

### ISSUE THREAD

**Issue by GwangYeol-Im** [woowacourse/javascript-subway#24]
안녕하세요, 브라운! 역 삭제 관련해서 오류가 있는 것 같아 확인차 이슈 올렸습니다.
현재 postman 에서 확인 결과 서버 에러가 아닐까 조심스레 추측해보고 있는데.. 확인 부탁드리겠습니다. 😅

## 🤦🏻 이슈 내용

<img width="1087" alt="스크린샷 2021-03-23 오전 12 08 52" src="https://user-images.githubusercontent.com/57053577/112011945-1893cb80-8b6c-11eb-9bbe-e747fdf46972.png">

```js
{
    "timestamp": "2021-03-22T15:14:31.033+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/stations/1"
}
```

## 🕵🏼 기대 결과

```js
HTTP/1.1 204 No Content
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Date: Mon, 22 Mar 2021 11:06:46 GMT
Keep-Alive: timeout=60
Connection: keep-alive
```

**Comment by gracefulBrown** [comment]
## 원인
- 기존 CORS 설정이 GET, POST 만 가능했음

## 해결 방법
- 모든 METHOD 요청에 대해 설정

```java
@Override
public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**").allowedMethods("*").allowedOriginPatterns("*");
}
```
