### ISSUE TITLE
지하철 역 생성이 아이디 별로 구분되지 않습니다!

### ISSUE THREAD

**Issue by 0307kwon** [woowacourse/javascript-subway#34]
## 🤦🏻 이슈 내용

지하철 역 생성이 아이디 별로 구분되지 않습니다.

예를 들어
mickey@naver.com 에서 `강남` 을 추가했을 경우
jum0@naver.com에서는 `강남`이 추가되지 않는 문제가 있습니다. 

## 🕵🏼 기대 결과

계정 내에서만 역이름이 중복되지 않는다면  
다른 계정에서 이미 추가한 역이름도 추가가 가능해야 할 것 같습니다. 

항상 감사합니다! 브라운 ㅎㅎ 😁

**Comment by zigsong** [comment]
## 지하철역 이름 수정 시 

## 🤦🏻 이슈 내용

지하철역 이름 수정 시, 변경하고자 하는 이름이 현재 계정이 아닌 다른 계정으로 이미 등록된 역 이름과 중복된 경우
400 error가 발생합니다. 

## 🕵🏼 기대 결과
현재 로그인 한 계정 내에서만 역 이름이 중복되지 않는다면, 원하는 이름으로 역 이름을 수정할 수 있어야 할 것 같습니다! ☺️☺️

**Comment by gracefulBrown** [comment]
해결 후 배포했습니다 확인 후 close 해주세요~

**Comment by 0307kwon** [comment]
![image](https://user-images.githubusercontent.com/48755175/112584893-18c9ea80-8e3c-11eb-96b1-c9ca47198432.png)

저희가 가진 mj@naver.com 아이디에 `강남`이 추가되어있는데
wnsah052@naver.com에서 `강남`이 여전히 추가가 되지 않습니다. ㅠㅠ 😢
확인 부탁드립니다 브라운! 😊

**Comment by gracefulBrown** [comment]
## 원인
unique 설정 해제 이후에도 디비에는 unique 설정이 남아 있었음

## 해결 방법
디비에서 직접 유니크 설정 제거
```
select distinct table_name, constraint_name from information_schema.constraints 

ALTER TABLE STATION DROP CONSTRAINT UK_GNNEUC0PEQ2QI08YFTDJHY7OK
ALTER TABLE LINE DROP CONSTRAINT UK_9NEY9DAVBULF79NMN9VG6K7TN
```
