### ISSUE TITLE
구간 추가에 대한 Issue 

### ISSUE THREAD

**Issue by ddongule** [woowacourse/javascript-subway#35]
### 2-1) B역와 C역 사이에 거리와 같은 구간을 추가했을 때(B-D: 거리 5)

- 추가 됨 (문제라고 생각합니다.)
        - 이유 : 이렇게 추가가 되면 D와 C역 사이의 거리가 0이 됨

## 🕵🏼 기대 결과 1
**Response**
  ```json
  역과 역 사이의 거리보다 좁은 거리를 입력해 주세요.
  ```

### 2-2) 거리:0, 시간:0 인 구간을 추가했을 때 

- 추가 됨	

## 🕵🏼 기대 결과 2
**Response**
  ```json
  거리와 시간은 1 이상인 값이어야 합니다.
  ```

**Comment by gracefulBrown** [comment]
해결됨
확인중

**Comment by ddongule** [comment]
해결 되었습니다! 감사합니다 >____< 🧡
![Screen Shot 2021-03-26 at 2 38 12 PM](https://user-images.githubusercontent.com/26598561/112587430-e8387f80-8e40-11eb-9279-8c6926a36aeb.png)
![Screen Shot 2021-03-26 at 2 38 31 PM](https://user-images.githubusercontent.com/26598561/112587462-f2f31480-8e40-11eb-879b-358392b38e2e.png)
