### ISSUE TITLE
지하철 노선 수정 PUT /lines/ 이 노선명을 필수적으로 변경해야합니다

### ISSUE THREAD

**Issue by jho2301** [woowacourse/javascript-subway#39]
## 🤦🏻 이슈 내용

노선 이름을 바꾸지 않고, 다른 값들을 수정해서 api 요청 시, `이미 존재하는 노선 이름입니다`라는 400 에러메시지 응답.

무조건 노선이름을 수정해야하는듯 보입니다

![image](https://user-images.githubusercontent.com/44419181/112628298-0f5d7400-8e76-11eb-9557-738cb2343326.png)

## 🕵🏼 기대 결과

노선이름을 수정하지 않고도 여타 값 수정 가능해야할 것 같습니다

**Comment by jho2301** [comment]
출발역. 도착역, 거리, 시간이 변경할 수 없는 값이라면 노선색만 바꾸었을때 바뀌어야할 것 같습니다

**Comment by gracefulBrown** [comment]
## 수정내용
이름이 다를때만 이름 중복 확인
